name: Pull Requests

on:
  pull_request:
    types: [ opened ]

permissions:
  contents: read
  pull-requests: write

jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: PullRequestHandler
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCOOP_BRANCH: develop
